title: Mi Blog
description: Más que un blog es el lugar donde organizo y hago backups de mis ideas
email: dmorfav@gmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
github_username: dmorfav
baseurl:      ""
locale:       "es"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
