title: Backup Brain
name: Backup Brain
description: Más que un blog es el lugar donde organizo y hago backups de mis ideas
email: dmorfav@gmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
github_username: dmorfav
baseurl: ""
locale: "es"

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
